library(RTextTools)
setwd(".//20news-bydate-train")
r<-read_data("train_data",type = "folder", index = "labels_talk_politics_misc.csv",warn=F)
doc_matrix <- create_matrix(r$Text.Data, language="english", removeNumbers=TRUE, stemWords=TRUE, removeSparseTerms=.998)
container <- create_container(doc_matrix, r$Labels, trainSize=1:2624,testSize = 2625:4370, virgin=FALSE)

SVM <- train_model(container,"SVM")
GLMNET <- train_model(container,"GLMNET")
MAXENT <- train_model(container,"MAXENT")
BOOSTING <- train_model(container,"BOOSTING")
#BAGGING <- train_model(container,"BAGGING")
RF <- train_model(container,"RF")
TREE <- train_model(container,"TREE")

SVM_CLASSIFY <- classify_model(container, SVM)
GLMNET_CLASSIFY <- classify_model(container, GLMNET)
MAXENT_CLASSIFY <- classify_model(container, MAXENT)
BOOSTING_CLASSIFY <- classify_model(container, BOOSTING)
#BAGGING_CLASSIFY <- classify_model(container, BAGGING)
RF_CLASSIFY <- classify_model(container, RF)
TREE_CLASSIFY <- classify_model(container, TREE)
analytics <- create_analytics(container, cbind(SVM_CLASSIFY, BOOSTING_CLASSIFY, GLMNET_CLASSIFY, TREE_CLASSIFY, MAXENT_CLASSIFY))
summary(analytics)
